activation: relu
agent_type: chain
center_complex: true
config: paper/potential_model/config_train.yml
cross_max_neighbors: 50
cross_max_radius: 40.0
data_dir: data
deviation_eps: 1
distance_emb_dim: 32
dropout_p: 0.1
edge_fdim: 0
ema_decay_rate: null
enable_plotting: true
enforce_stability: false
eval_every: 1
featurizer: base
grad_clip_value: null
group_name: dock_score_hetero-dips_db5_energy_pairs-cluster
job_type: train
log_dir: ./logs
log_every: 1
loss_type: l1
lr: 0.001
lr_sched_metric: val_loss
lr_sched_metric_goal: min
max_neighbors: 50
max_radius: 15
max_tr_decoys: 0.0
mode: base
model: dock_score_hetero
n_conv_layers: 4
n_deviations: 0
n_epochs: 200
n_gpus: 4
n_s: 16
n_v: 4
node_fdim: 145
norm_method: minmax
notes: null
num_decoys: 10
num_workers: 1
only_penalize_diff: false
optim_name: adam
predict_rmsd: false
project_name: dockgame
ref_choice: random
resolution: c_alpha
restore_from: null
run_name: dock_score_hetero-dips_db5_energy_pairs-cluster-r087vxt8
scheduler: none
scheduler_mode: min
scheduler_patience: 10
score_fn_decoys: dock_low_res
sh_lmax: 2
step_every: 1
train_bs: 5
train_complex_dir: pairs-pruned
train_complex_list_file: pairs-postprocessed-train.txt
train_dataset: dips
val_bs: 10
val_complex_dir: complexes
val_complex_list_file: val.txt
val_dataset: db5
val_num_decoys: 100
w_energy: 0.0
w_energy_diff: 0.0
w_energy_ref: 0.0
w_rmsd: 0.0
w_stability: 1.0
wandb_entity: null
wandb_mode: online
weight_decay: 0.0
