activation: relu
agent_type: chain
center_complex: true
center_dist_emb_dim: 32
center_max_radius: 30.0
config: paper/score_model/config_train.yml
cross_cutoff_threshold: 40.0
cross_dist_emb_dim: 32
cross_max_neighbors: 1000
cross_max_radius: 80.0
data_dir: data
deviation_eps: 0.1
distance_emb_dim: 32
dropout_p: 0
dynamic_max_cross: true
edge_fdim: 0
ema_decay_rate: null
embed_scale: 10000
embed_type: sinusoidal
enable_plotting: true
enforce_stability: false
eval_every: 1
featurizer: base
grad_clip_value: 1.0
group_name: db5-finetuning
inference_every: 10
inference_goal: max
inference_metric: val_inference_rmsd_lt10
inference_multiplicity: 10
inference_steps: 50
job_type: null
log_dir: logs
log_every: 1
lr: 0.0005
lr_sched_metric: val_inference_min_rmsd_lt5
lr_sched_metric_goal: min
max_neighbors: 30
max_radius: 20
model: score
n_conv_layers: 4
n_deviations: 0
n_epochs: 5000
n_gpus: 4
n_s: 16
n_v: 4
node_encoder_type: separate
node_fdim: 145
notes: null
num_inference_complexes: 10
num_workers: 1
optim_name: adam
pert_strategy: all-but-one
project_name: dockgame-db5-tuning
resolution: c_alpha
restore_from: trained_models/dips_medium_model/best_model.pt
rot_sigma_max: 1.65
rot_sigma_min: 0.01
run_name: ns=16-nv=4-nl=4-cross=80-1000-pert=allbutone-t=20-rz2xo251
same_t_for_agent: true
scale_by_sigma: true
scheduler: null
scheduler_goal: max
scheduler_mode: min
scheduler_patience: 40
sh_lmax: 2
sigma_emb_dim: 32
step_every: 4
time_embed_scale: 10000
time_embed_type: sinusoidal
timepoints_per_complex: 20
tr_sigma_max: 25.0
tr_sigma_min: 0.01
train_bs: 4
train_complex_dir: complexes
train_complex_list_file: complexes-train.txt
train_dataset: db5
train_size_sorted: false
transform: ma_noise
val_bs: 4
val_complex_dir: null
val_complex_list_file: complexes-val.txt
val_dataset: null
val_size_sorted: false
w_rot: 0.5
w_tr: 0.5
wandb_mode: online
weight_decay: 0.0
